### ISSUE TITLE
Do we need a 'master' branch?

### ISSUE THREAD

**Issue by dmcwo** [UCLALibrary/research-tips-2#1]
I've been wondering if it would simplify things to delete the 'master' branch when we're using these repos for web publishing. We would then set the gh-pages branch to be the master, and any feature development could live in their own branches.

What do you think? Any unanticipated side effects of this?

**Comment by caitlinmeyer** [comment]
I think that's a great idea. I don't foresee any issues.. it may even be better because it's really easy to accidentally do a bunch of work and commits in master and not realize why changes aren't showing up on the published page.

**Comment by dmcwo** [comment]
OK - changed the default branch to gh-pages and deleted the "master" branch. Now we can use branches for significant features work. Hope this solution works out. Looks like the deleted master branch can be restored if needed in the future. Thanks!
